### ISSUE TITLE
Loss of functions?

### ISSUE THREAD

**Issue by austinj** [ChristopherLucas/MatchingFrontier#33]
It looks as though `plotFrontier()` and `plotEstimates()` have been removed from the package. Has this functionality been removed permanently?

**Comment by ChristopherLucas** [comment]
No, now you can just call plot() on the frontier and estimates object. E.G., see https://github.com/ChristopherLucas/MatchingFrontier/blob/master/R/plot.frontierEstimates.R. 

The original functions are still in the package, just not in the namespace. They get directly called when you call plot() on the appropriate objects.

**Comment by ChristopherLucas** [comment]
This is a good reminder that the documentation needs to be updated. Thanks!

**Comment by austinj** [comment]
Thanks! I appreciate it.
